// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/account/v1/api_phone_number.proto

package v1

import (
	fmt "fmt"
	v1 "github.com/AlpacaLabs/protorepo-pagination-go/alpacalabs/pagination/v1"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetPhoneNumbersRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetPhoneNumbersRequest) Reset()         { *m = GetPhoneNumbersRequest{} }
func (m *GetPhoneNumbersRequest) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumbersRequest) ProtoMessage()    {}
func (*GetPhoneNumbersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{0}
}

func (m *GetPhoneNumbersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumbersRequest.Unmarshal(m, b)
}
func (m *GetPhoneNumbersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumbersRequest.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumbersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumbersRequest.Merge(m, src)
}
func (m *GetPhoneNumbersRequest) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumbersRequest.Size(m)
}
func (m *GetPhoneNumbersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumbersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumbersRequest proto.InternalMessageInfo

func (m *GetPhoneNumbersRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

type GetPhoneNumbersResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	PhoneNumbers         []*PhoneNumber     `protobuf:"bytes,2,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetPhoneNumbersResponse) Reset()         { *m = GetPhoneNumbersResponse{} }
func (m *GetPhoneNumbersResponse) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumbersResponse) ProtoMessage()    {}
func (*GetPhoneNumbersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{1}
}

func (m *GetPhoneNumbersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumbersResponse.Unmarshal(m, b)
}
func (m *GetPhoneNumbersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumbersResponse.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumbersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumbersResponse.Merge(m, src)
}
func (m *GetPhoneNumbersResponse) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumbersResponse.Size(m)
}
func (m *GetPhoneNumbersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumbersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumbersResponse proto.InternalMessageInfo

func (m *GetPhoneNumbersResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetPhoneNumbersResponse) GetPhoneNumbers() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

type GetPhoneNumberRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPhoneNumberRequest) Reset()         { *m = GetPhoneNumberRequest{} }
func (m *GetPhoneNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumberRequest) ProtoMessage()    {}
func (*GetPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{2}
}

func (m *GetPhoneNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumberRequest.Unmarshal(m, b)
}
func (m *GetPhoneNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumberRequest.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumberRequest.Merge(m, src)
}
func (m *GetPhoneNumberRequest) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumberRequest.Size(m)
}
func (m *GetPhoneNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumberRequest proto.InternalMessageInfo

func (m *GetPhoneNumberRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPhoneNumberResponse struct {
	PhoneNumber          *PhoneNumber `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPhoneNumberResponse) Reset()         { *m = GetPhoneNumberResponse{} }
func (m *GetPhoneNumberResponse) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumberResponse) ProtoMessage()    {}
func (*GetPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{3}
}

func (m *GetPhoneNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumberResponse.Unmarshal(m, b)
}
func (m *GetPhoneNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumberResponse.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumberResponse.Merge(m, src)
}
func (m *GetPhoneNumberResponse) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumberResponse.Size(m)
}
func (m *GetPhoneNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumberResponse proto.InternalMessageInfo

func (m *GetPhoneNumberResponse) GetPhoneNumber() *PhoneNumber {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

type RegisterPhoneNumberRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterPhoneNumberRequest) Reset()         { *m = RegisterPhoneNumberRequest{} }
func (m *RegisterPhoneNumberRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterPhoneNumberRequest) ProtoMessage()    {}
func (*RegisterPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{4}
}

func (m *RegisterPhoneNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterPhoneNumberRequest.Unmarshal(m, b)
}
func (m *RegisterPhoneNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterPhoneNumberRequest.Marshal(b, m, deterministic)
}
func (m *RegisterPhoneNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterPhoneNumberRequest.Merge(m, src)
}
func (m *RegisterPhoneNumberRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterPhoneNumberRequest.Size(m)
}
func (m *RegisterPhoneNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterPhoneNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterPhoneNumberRequest proto.InternalMessageInfo

func (m *RegisterPhoneNumberRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *RegisterPhoneNumberRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type RegisterPhoneNumberResponse struct {
	PhoneNumber          *PhoneNumber `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterPhoneNumberResponse) Reset()         { *m = RegisterPhoneNumberResponse{} }
func (m *RegisterPhoneNumberResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterPhoneNumberResponse) ProtoMessage()    {}
func (*RegisterPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{5}
}

func (m *RegisterPhoneNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterPhoneNumberResponse.Unmarshal(m, b)
}
func (m *RegisterPhoneNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterPhoneNumberResponse.Marshal(b, m, deterministic)
}
func (m *RegisterPhoneNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterPhoneNumberResponse.Merge(m, src)
}
func (m *RegisterPhoneNumberResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterPhoneNumberResponse.Size(m)
}
func (m *RegisterPhoneNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterPhoneNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterPhoneNumberResponse proto.InternalMessageInfo

func (m *RegisterPhoneNumberResponse) GetPhoneNumber() *PhoneNumber {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

type UnregisterPhoneNumberRequest struct {
	PhoneNumberId        string   `protobuf:"bytes,1,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterPhoneNumberRequest) Reset()         { *m = UnregisterPhoneNumberRequest{} }
func (m *UnregisterPhoneNumberRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterPhoneNumberRequest) ProtoMessage()    {}
func (*UnregisterPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{6}
}

func (m *UnregisterPhoneNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterPhoneNumberRequest.Unmarshal(m, b)
}
func (m *UnregisterPhoneNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterPhoneNumberRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterPhoneNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterPhoneNumberRequest.Merge(m, src)
}
func (m *UnregisterPhoneNumberRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterPhoneNumberRequest.Size(m)
}
func (m *UnregisterPhoneNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterPhoneNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterPhoneNumberRequest proto.InternalMessageInfo

func (m *UnregisterPhoneNumberRequest) GetPhoneNumberId() string {
	if m != nil {
		return m.PhoneNumberId
	}
	return ""
}

type UnregisterPhoneNumberResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterPhoneNumberResponse) Reset()         { *m = UnregisterPhoneNumberResponse{} }
func (m *UnregisterPhoneNumberResponse) String() string { return proto.CompactTextString(m) }
func (*UnregisterPhoneNumberResponse) ProtoMessage()    {}
func (*UnregisterPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{7}
}

func (m *UnregisterPhoneNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterPhoneNumberResponse.Unmarshal(m, b)
}
func (m *UnregisterPhoneNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterPhoneNumberResponse.Marshal(b, m, deterministic)
}
func (m *UnregisterPhoneNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterPhoneNumberResponse.Merge(m, src)
}
func (m *UnregisterPhoneNumberResponse) XXX_Size() int {
	return xxx_messageInfo_UnregisterPhoneNumberResponse.Size(m)
}
func (m *UnregisterPhoneNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterPhoneNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterPhoneNumberResponse proto.InternalMessageInfo

type ConfirmPhoneNumberRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,2,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPhoneNumberRequest) Reset()         { *m = ConfirmPhoneNumberRequest{} }
func (m *ConfirmPhoneNumberRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmPhoneNumberRequest) ProtoMessage()    {}
func (*ConfirmPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{8}
}

func (m *ConfirmPhoneNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Unmarshal(m, b)
}
func (m *ConfirmPhoneNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmPhoneNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPhoneNumberRequest.Merge(m, src)
}
func (m *ConfirmPhoneNumberRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Size(m)
}
func (m *ConfirmPhoneNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPhoneNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPhoneNumberRequest proto.InternalMessageInfo

func (m *ConfirmPhoneNumberRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *ConfirmPhoneNumberRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

type ConfirmPhoneNumberResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPhoneNumberResponse) Reset()         { *m = ConfirmPhoneNumberResponse{} }
func (m *ConfirmPhoneNumberResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmPhoneNumberResponse) ProtoMessage()    {}
func (*ConfirmPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{9}
}

func (m *ConfirmPhoneNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Unmarshal(m, b)
}
func (m *ConfirmPhoneNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmPhoneNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPhoneNumberResponse.Merge(m, src)
}
func (m *ConfirmPhoneNumberResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Size(m)
}
func (m *ConfirmPhoneNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPhoneNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPhoneNumberResponse proto.InternalMessageInfo

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetPhoneNumbersForAccountIDRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	AccountId            string            `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetPhoneNumbersForAccountIDRequest) Reset()         { *m = GetPhoneNumbersForAccountIDRequest{} }
func (m *GetPhoneNumbersForAccountIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumbersForAccountIDRequest) ProtoMessage()    {}
func (*GetPhoneNumbersForAccountIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{10}
}

func (m *GetPhoneNumbersForAccountIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDRequest.Unmarshal(m, b)
}
func (m *GetPhoneNumbersForAccountIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDRequest.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumbersForAccountIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumbersForAccountIDRequest.Merge(m, src)
}
func (m *GetPhoneNumbersForAccountIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDRequest.Size(m)
}
func (m *GetPhoneNumbersForAccountIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumbersForAccountIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumbersForAccountIDRequest proto.InternalMessageInfo

func (m *GetPhoneNumbersForAccountIDRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

func (m *GetPhoneNumbersForAccountIDRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetPhoneNumbersForAccountIDResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	PhoneNumbers         []*PhoneNumber     `protobuf:"bytes,2,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetPhoneNumbersForAccountIDResponse) Reset()         { *m = GetPhoneNumbersForAccountIDResponse{} }
func (m *GetPhoneNumbersForAccountIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumbersForAccountIDResponse) ProtoMessage()    {}
func (*GetPhoneNumbersForAccountIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{11}
}

func (m *GetPhoneNumbersForAccountIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDResponse.Unmarshal(m, b)
}
func (m *GetPhoneNumbersForAccountIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDResponse.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumbersForAccountIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumbersForAccountIDResponse.Merge(m, src)
}
func (m *GetPhoneNumbersForAccountIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDResponse.Size(m)
}
func (m *GetPhoneNumbersForAccountIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumbersForAccountIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumbersForAccountIDResponse proto.InternalMessageInfo

func (m *GetPhoneNumbersForAccountIDResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetPhoneNumbersForAccountIDResponse) GetPhoneNumbers() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPhoneNumbersRequest)(nil), "alpacalabs.account.v1.GetPhoneNumbersRequest")
	proto.RegisterType((*GetPhoneNumbersResponse)(nil), "alpacalabs.account.v1.GetPhoneNumbersResponse")
	proto.RegisterType((*GetPhoneNumberRequest)(nil), "alpacalabs.account.v1.GetPhoneNumberRequest")
	proto.RegisterType((*GetPhoneNumberResponse)(nil), "alpacalabs.account.v1.GetPhoneNumberResponse")
	proto.RegisterType((*RegisterPhoneNumberRequest)(nil), "alpacalabs.account.v1.RegisterPhoneNumberRequest")
	proto.RegisterType((*RegisterPhoneNumberResponse)(nil), "alpacalabs.account.v1.RegisterPhoneNumberResponse")
	proto.RegisterType((*UnregisterPhoneNumberRequest)(nil), "alpacalabs.account.v1.UnregisterPhoneNumberRequest")
	proto.RegisterType((*UnregisterPhoneNumberResponse)(nil), "alpacalabs.account.v1.UnregisterPhoneNumberResponse")
	proto.RegisterType((*ConfirmPhoneNumberRequest)(nil), "alpacalabs.account.v1.ConfirmPhoneNumberRequest")
	proto.RegisterType((*ConfirmPhoneNumberResponse)(nil), "alpacalabs.account.v1.ConfirmPhoneNumberResponse")
	proto.RegisterType((*GetPhoneNumbersForAccountIDRequest)(nil), "alpacalabs.account.v1.GetPhoneNumbersForAccountIDRequest")
	proto.RegisterType((*GetPhoneNumbersForAccountIDResponse)(nil), "alpacalabs.account.v1.GetPhoneNumbersForAccountIDResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/account/v1/api_phone_number.proto", fileDescriptor_b91d3d7e8a819384)
}

var fileDescriptor_b91d3d7e8a819384 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x95, 0x4c, 0x42, 0xea, 0xe9, 0x9f, 0x41, 0xa4, 0x42, 0x57, 0x36, 0x31, 0x3c, 0x89,
	0x55, 0x82, 0x39, 0xca, 0x78, 0x01, 0xba, 0xc2, 0xa6, 0x49, 0xd3, 0x54, 0x22, 0xb1, 0x0b, 0x34,
	0x11, 0xb9, 0x8e, 0x49, 0x2d, 0xd6, 0xd8, 0x38, 0x49, 0x5f, 0x84, 0x37, 0x80, 0x3b, 0xee, 0x79,
	0x00, 0x6e, 0x79, 0x2a, 0x94, 0xc4, 0xb4, 0xee, 0xe6, 0x31, 0x84, 0x40, 0xda, 0x65, 0x8e, 0xcf,
	0xf9, 0xbe, 0xdf, 0xf9, 0x92, 0x18, 0x9e, 0x91, 0x0b, 0x49, 0x28, 0xb9, 0x20, 0x93, 0xcc, 0x27,
	0x94, 0x8a, 0x22, 0xcd, 0xfd, 0x79, 0xe0, 0x13, 0xc9, 0x23, 0x39, 0x15, 0x29, 0x8b, 0xd2, 0x62,
	0x36, 0x61, 0x0a, 0x4b, 0x25, 0x72, 0xe1, 0x75, 0x97, 0xdd, 0x58, 0x77, 0xe3, 0x79, 0xd0, 0xdf,
	0x31, 0x44, 0x24, 0x49, 0x78, 0x4a, 0x72, 0x2e, 0xd2, 0x52, 0x47, 0x92, 0x84, 0xd5, 0xb3, 0xfd,
	0x81, 0xdd, 0xe9, 0xaa, 0x0b, 0x9a, 0xc2, 0xfd, 0x23, 0x96, 0x8f, 0xcb, 0x83, 0xd3, 0xaa, 0x9e,
	0x85, 0xec, 0x63, 0xc1, 0xb2, 0xdc, 0x3b, 0x85, 0x0e, 0x2d, 0x54, 0x26, 0x54, 0xa4, 0xea, 0x4a,
	0xcf, 0xd9, 0x76, 0x06, 0xcd, 0xfd, 0x5d, 0x6c, 0x80, 0x2d, 0x09, 0xf0, 0x3c, 0xc0, 0xa3, 0xaa,
	0x5f, 0x0b, 0x84, 0x6d, 0x6a, 0x3e, 0xa2, 0x6f, 0x0e, 0x3c, 0xb8, 0x62, 0x95, 0x49, 0x91, 0x66,
	0xcc, 0x7b, 0x0d, 0xeb, 0x0b, 0xaf, 0xba, 0xa4, 0xcd, 0x06, 0x37, 0x9b, 0xd5, 0xfd, 0x61, 0x87,
	0xae, 0x3c, 0x7b, 0x47, 0xd0, 0x36, 0xd7, 0xcd, 0x7a, 0xee, 0xf6, 0xda, 0xa0, 0xb9, 0x8f, 0xb0,
	0x35, 0x56, 0x6c, 0x60, 0x85, 0x2d, 0x69, 0x30, 0xa2, 0x5d, 0xe8, 0xae, 0x62, 0xff, 0x0a, 0xa8,
	0x03, 0x2e, 0x8f, 0x2b, 0xce, 0x46, 0xe8, 0xf2, 0x18, 0x45, 0x97, 0xa3, 0x5c, 0xb0, 0xbc, 0x82,
	0x96, 0xc9, 0xa2, 0x77, 0xfb, 0x13, 0x94, 0xa6, 0x81, 0x82, 0xde, 0x41, 0x3f, 0x64, 0x09, 0xcf,
	0x72, 0xa6, 0x2c, 0x38, 0x8f, 0x2d, 0x26, 0x8d, 0x15, 0x01, 0x6f, 0x0b, 0x40, 0xfb, 0x44, 0x3c,
	0xee, 0xb9, 0x55, 0x43, 0x43, 0x57, 0x8e, 0x63, 0x14, 0xc3, 0x43, 0xab, 0xfe, 0xbf, 0xdd, 0xe2,
	0x10, 0x36, 0xdf, 0xa4, 0xea, 0xfa, 0x3d, 0x9e, 0xc0, 0xba, 0x69, 0x13, 0x2d, 0x32, 0x6e, 0x1b,
	0x2a, 0xc7, 0x31, 0x7a, 0x04, 0x5b, 0xd7, 0xe8, 0xd4, 0xbc, 0xe8, 0x03, 0x6c, 0x8c, 0x44, 0xfa,
	0x9e, 0xab, 0xd9, 0xdf, 0xa5, 0xf5, 0x14, 0xee, 0xd1, 0x7a, 0xbe, 0xfa, 0xe6, 0x22, 0x2a, 0x62,
	0xa6, 0x43, 0xbb, 0x6b, 0x1e, 0x8c, 0x44, 0xcc, 0xd0, 0x26, 0xf4, 0x6d, 0x66, 0x1a, 0xe5, 0x93,
	0x03, 0xe8, 0xd2, 0xb7, 0x7f, 0x28, 0xd4, 0x50, 0x27, 0xff, 0xf2, 0x3f, 0xfd, 0x72, 0x37, 0xbd,
	0xef, 0xef, 0x0e, 0xec, 0xfc, 0x96, 0xea, 0xf6, 0xff, 0x9d, 0x07, 0x5f, 0x1c, 0xd8, 0xa0, 0x62,
	0x66, 0x9f, 0x3b, 0x68, 0xe9, 0x65, 0xc6, 0xe5, 0x5d, 0x37, 0x76, 0xde, 0xbe, 0x48, 0x78, 0x3e,
	0x2d, 0x26, 0x98, 0x8a, 0x99, 0x3f, 0xac, 0x26, 0x4e, 0xaa, 0x7b, 0xb4, 0x3c, 0x56, 0x4c, 0x8a,
	0x3d, 0x3d, 0xbb, 0x97, 0x08, 0xdf, 0x7a, 0x85, 0x7e, 0x76, 0xd7, 0x86, 0x27, 0xc3, 0xaf, 0x6e,
	0x77, 0x39, 0x8d, 0xb5, 0x07, 0x3e, 0x0b, 0x7e, 0x98, 0xf5, 0x73, 0x5d, 0x3f, 0x3f, 0x0b, 0x26,
	0x77, 0x2a, 0x87, 0xe7, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x43, 0xe7, 0x9d, 0x02, 0x06,
	0x00, 0x00,
}
