// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/account/v1/api_email.proto

package v1

import (
	fmt "fmt"
	v1 "github.com/AlpacaLabs/protorepo-pagination-go/alpacalabs/pagination/v1"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetEmailAddressesRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEmailAddressesRequest) Reset()         { *m = GetEmailAddressesRequest{} }
func (m *GetEmailAddressesRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesRequest) ProtoMessage()    {}
func (*GetEmailAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{0}
}

func (m *GetEmailAddressesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesRequest.Unmarshal(m, b)
}
func (m *GetEmailAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesRequest.Merge(m, src)
}
func (m *GetEmailAddressesRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesRequest.Size(m)
}
func (m *GetEmailAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesRequest proto.InternalMessageInfo

func (m *GetEmailAddressesRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

type GetEmailAddressesResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	EmailAddresses       []*EmailAddress    `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetEmailAddressesResponse) Reset()         { *m = GetEmailAddressesResponse{} }
func (m *GetEmailAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesResponse) ProtoMessage()    {}
func (*GetEmailAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{1}
}

func (m *GetEmailAddressesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesResponse.Unmarshal(m, b)
}
func (m *GetEmailAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesResponse.Merge(m, src)
}
func (m *GetEmailAddressesResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesResponse.Size(m)
}
func (m *GetEmailAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesResponse proto.InternalMessageInfo

func (m *GetEmailAddressesResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetEmailAddressesResponse) GetEmailAddresses() []*EmailAddress {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

type GetEmailAddressByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEmailAddressByIDRequest) Reset()         { *m = GetEmailAddressByIDRequest{} }
func (m *GetEmailAddressByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressByIDRequest) ProtoMessage()    {}
func (*GetEmailAddressByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{2}
}

func (m *GetEmailAddressByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressByIDRequest.Unmarshal(m, b)
}
func (m *GetEmailAddressByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressByIDRequest.Merge(m, src)
}
func (m *GetEmailAddressByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressByIDRequest.Size(m)
}
func (m *GetEmailAddressByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressByIDRequest proto.InternalMessageInfo

func (m *GetEmailAddressByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetEmailAddressByIDResponse struct {
	EmailAddress         *EmailAddress `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetEmailAddressByIDResponse) Reset()         { *m = GetEmailAddressByIDResponse{} }
func (m *GetEmailAddressByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressByIDResponse) ProtoMessage()    {}
func (*GetEmailAddressByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{3}
}

func (m *GetEmailAddressByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressByIDResponse.Unmarshal(m, b)
}
func (m *GetEmailAddressByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressByIDResponse.Merge(m, src)
}
func (m *GetEmailAddressByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressByIDResponse.Size(m)
}
func (m *GetEmailAddressByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressByIDResponse proto.InternalMessageInfo

func (m *GetEmailAddressByIDResponse) GetEmailAddress() *EmailAddress {
	if m != nil {
		return m.EmailAddress
	}
	return nil
}

type AddEmailAddressRequest struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddEmailAddressRequest) Reset()         { *m = AddEmailAddressRequest{} }
func (m *AddEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*AddEmailAddressRequest) ProtoMessage()    {}
func (*AddEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{4}
}

func (m *AddEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEmailAddressRequest.Unmarshal(m, b)
}
func (m *AddEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *AddEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEmailAddressRequest.Merge(m, src)
}
func (m *AddEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_AddEmailAddressRequest.Size(m)
}
func (m *AddEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddEmailAddressRequest proto.InternalMessageInfo

func (m *AddEmailAddressRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *AddEmailAddressRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type AddEmailAddressResponse struct {
	EmailAddress         *EmailAddress `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddEmailAddressResponse) Reset()         { *m = AddEmailAddressResponse{} }
func (m *AddEmailAddressResponse) String() string { return proto.CompactTextString(m) }
func (*AddEmailAddressResponse) ProtoMessage()    {}
func (*AddEmailAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{5}
}

func (m *AddEmailAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddEmailAddressResponse.Unmarshal(m, b)
}
func (m *AddEmailAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddEmailAddressResponse.Marshal(b, m, deterministic)
}
func (m *AddEmailAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddEmailAddressResponse.Merge(m, src)
}
func (m *AddEmailAddressResponse) XXX_Size() int {
	return xxx_messageInfo_AddEmailAddressResponse.Size(m)
}
func (m *AddEmailAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddEmailAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddEmailAddressResponse proto.InternalMessageInfo

func (m *AddEmailAddressResponse) GetEmailAddress() *EmailAddress {
	if m != nil {
		return m.EmailAddress
	}
	return nil
}

type ConfirmEmailAddressRequest struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,2,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailAddressRequest) Reset()         { *m = ConfirmEmailAddressRequest{} }
func (m *ConfirmEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailAddressRequest) ProtoMessage()    {}
func (*ConfirmEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{6}
}

func (m *ConfirmEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Unmarshal(m, b)
}
func (m *ConfirmEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailAddressRequest.Merge(m, src)
}
func (m *ConfirmEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Size(m)
}
func (m *ConfirmEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailAddressRequest proto.InternalMessageInfo

func (m *ConfirmEmailAddressRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *ConfirmEmailAddressRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

type ConfirmEmailAddressResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailAddressResponse) Reset()         { *m = ConfirmEmailAddressResponse{} }
func (m *ConfirmEmailAddressResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailAddressResponse) ProtoMessage()    {}
func (*ConfirmEmailAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{7}
}

func (m *ConfirmEmailAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailAddressResponse.Unmarshal(m, b)
}
func (m *ConfirmEmailAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailAddressResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailAddressResponse.Merge(m, src)
}
func (m *ConfirmEmailAddressResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailAddressResponse.Size(m)
}
func (m *ConfirmEmailAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailAddressResponse proto.InternalMessageInfo

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetEmailAddressesForAccountIDRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	AccountId            string            `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEmailAddressesForAccountIDRequest) Reset()         { *m = GetEmailAddressesForAccountIDRequest{} }
func (m *GetEmailAddressesForAccountIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesForAccountIDRequest) ProtoMessage()    {}
func (*GetEmailAddressesForAccountIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{8}
}

func (m *GetEmailAddressesForAccountIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Unmarshal(m, b)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Merge(m, src)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Size(m)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesForAccountIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesForAccountIDRequest proto.InternalMessageInfo

func (m *GetEmailAddressesForAccountIDRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

func (m *GetEmailAddressesForAccountIDRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetEmailAddressesForAccountIDResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	EmailAddresses       []*EmailAddress    `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetEmailAddressesForAccountIDResponse) Reset()         { *m = GetEmailAddressesForAccountIDResponse{} }
func (m *GetEmailAddressesForAccountIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesForAccountIDResponse) ProtoMessage()    {}
func (*GetEmailAddressesForAccountIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{9}
}

func (m *GetEmailAddressesForAccountIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Unmarshal(m, b)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Merge(m, src)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Size(m)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesForAccountIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesForAccountIDResponse proto.InternalMessageInfo

func (m *GetEmailAddressesForAccountIDResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetEmailAddressesForAccountIDResponse) GetEmailAddresses() []*EmailAddress {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

func init() {
	proto.RegisterType((*GetEmailAddressesRequest)(nil), "alpacalabs.account.v1.GetEmailAddressesRequest")
	proto.RegisterType((*GetEmailAddressesResponse)(nil), "alpacalabs.account.v1.GetEmailAddressesResponse")
	proto.RegisterType((*GetEmailAddressByIDRequest)(nil), "alpacalabs.account.v1.GetEmailAddressByIDRequest")
	proto.RegisterType((*GetEmailAddressByIDResponse)(nil), "alpacalabs.account.v1.GetEmailAddressByIDResponse")
	proto.RegisterType((*AddEmailAddressRequest)(nil), "alpacalabs.account.v1.AddEmailAddressRequest")
	proto.RegisterType((*AddEmailAddressResponse)(nil), "alpacalabs.account.v1.AddEmailAddressResponse")
	proto.RegisterType((*ConfirmEmailAddressRequest)(nil), "alpacalabs.account.v1.ConfirmEmailAddressRequest")
	proto.RegisterType((*ConfirmEmailAddressResponse)(nil), "alpacalabs.account.v1.ConfirmEmailAddressResponse")
	proto.RegisterType((*GetEmailAddressesForAccountIDRequest)(nil), "alpacalabs.account.v1.GetEmailAddressesForAccountIDRequest")
	proto.RegisterType((*GetEmailAddressesForAccountIDResponse)(nil), "alpacalabs.account.v1.GetEmailAddressesForAccountIDResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/account/v1/api_email.proto", fileDescriptor_5b7338160ae739ad)
}

var fileDescriptor_5b7338160ae739ad = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x55, 0x32, 0x09, 0xa9, 0xdf, 0xb6, 0x0e, 0x22, 0x0d, 0xba, 0x4e, 0x93, 0x46, 0xca, 0x44,
	0x25, 0x98, 0xa3, 0x8c, 0x17, 0x20, 0xed, 0xf8, 0x99, 0x54, 0xa1, 0x91, 0x8b, 0x5d, 0xa0, 0x4a,
	0x91, 0x6b, 0x9b, 0x60, 0xd4, 0xc6, 0xc1, 0x4e, 0x2b, 0xf1, 0x20, 0xbc, 0x00, 0xdc, 0xf1, 0x0c,
	0x3c, 0x00, 0xe2, 0xa9, 0x50, 0x1d, 0x8f, 0x3a, 0xd4, 0x52, 0x11, 0x82, 0x8b, 0x5d, 0xe6, 0xf8,
	0x9c, 0xef, 0x9c, 0xe3, 0xd8, 0x86, 0x13, 0x3c, 0x2d, 0x31, 0xc1, 0x53, 0x3c, 0x51, 0x11, 0x26,
	0x44, 0xcc, 0x8b, 0x2a, 0x5a, 0xc4, 0x11, 0x2e, 0x79, 0xc6, 0x66, 0x98, 0x4f, 0x51, 0x29, 0x45,
	0x25, 0x82, 0xfd, 0x15, 0x0d, 0x19, 0x1a, 0x5a, 0xc4, 0xdd, 0x9e, 0xa5, 0x2e, 0x71, 0xce, 0x0b,
	0x5c, 0x71, 0x51, 0x2c, 0x07, 0x94, 0x38, 0x67, 0xb5, 0xb6, 0x7b, 0xdf, 0x6d, 0x61, 0x8d, 0x0f,
	0xdf, 0x43, 0xe7, 0x05, 0xab, 0x9e, 0x2d, 0x91, 0x84, 0x52, 0xc9, 0x94, 0x62, 0x2a, 0x65, 0x1f,
	0xe6, 0x4c, 0x55, 0xc1, 0x2b, 0x68, 0x93, 0xb9, 0x54, 0x42, 0x66, 0xb2, 0x46, 0x3a, 0xde, 0xb1,
	0xd7, 0xdf, 0x3e, 0x7b, 0x88, 0xac, 0x4c, 0x2b, 0x73, 0xb4, 0x88, 0xd1, 0x50, 0xf3, 0xcd, 0x80,
	0x74, 0x97, 0xd8, 0x9f, 0xe1, 0x37, 0x0f, 0x0e, 0x1c, 0x66, 0xaa, 0x14, 0x85, 0x62, 0xc1, 0x6b,
	0xd8, 0xfb, 0xe5, 0x56, 0x43, 0xc6, 0xae, 0xbf, 0xd9, 0xae, 0xe6, 0xa7, 0x6d, 0xd2, 0xf8, 0x0e,
	0x46, 0xb0, 0xa7, 0xbb, 0x66, 0xf8, 0xda, 0xad, 0xe3, 0x1f, 0x6f, 0xf5, 0xb7, 0xcf, 0x7a, 0xc8,
	0xb9, 0xab, 0xc8, 0x8e, 0x96, 0xb6, 0x59, 0x23, 0x68, 0xf8, 0x18, 0xba, 0xbf, 0xa5, 0x1f, 0x7c,
	0xbc, 0x38, 0xbf, 0xde, 0xac, 0x36, 0xf8, 0x9c, 0xea, 0xc4, 0xad, 0xd4, 0xe7, 0x34, 0xcc, 0xe1,
	0xd0, 0xc9, 0x36, 0xd1, 0x5e, 0xc2, 0x6e, 0x23, 0x9a, 0xe9, 0xfa, 0x47, 0xc1, 0x76, 0xec, 0x60,
	0xe1, 0x18, 0xee, 0x26, 0x94, 0x36, 0x08, 0x26, 0x52, 0xcf, 0xe5, 0xd1, 0x6a, 0xca, 0x83, 0x23,
	0x00, 0xe3, 0x93, 0x71, 0xda, 0xf1, 0x35, 0xa3, 0x65, 0x90, 0x0b, 0x1a, 0x12, 0xb8, 0xb7, 0x36,
	0xfd, 0x9f, 0x57, 0x28, 0xa0, 0x3b, 0x14, 0xc5, 0x5b, 0x2e, 0x67, 0x7f, 0x5d, 0xe3, 0x11, 0xdc,
	0x21, 0xf5, 0x08, 0x7d, 0x38, 0x32, 0x22, 0x28, 0x33, 0x6d, 0x6e, 0xdb, 0x0b, 0x43, 0x41, 0x59,
	0x78, 0x04, 0x87, 0x4e, 0xbf, 0xba, 0x58, 0xf8, 0xc9, 0x83, 0x07, 0x6b, 0xe7, 0xf4, 0xb9, 0x90,
	0x89, 0xd9, 0x95, 0xf3, 0xff, 0x74, 0x41, 0x36, 0xfd, 0x8b, 0xef, 0x1e, 0x9c, 0x6c, 0xc8, 0x75,
	0x43, 0xee, 0xd2, 0xe0, 0x8b, 0x07, 0x07, 0x44, 0xcc, 0xdc, 0xd2, 0xc1, 0x8e, 0x69, 0x74, 0xb9,
	0x7c, 0xa2, 0x2e, 0xbd, 0x37, 0x4f, 0x73, 0x5e, 0xbd, 0x9b, 0x4f, 0x10, 0x11, 0xb3, 0x28, 0xd1,
	0x8a, 0x91, 0x7e, 0xf7, 0x96, 0xcb, 0x92, 0x95, 0xe2, 0xd4, 0x68, 0x4f, 0x73, 0x11, 0x39, 0x9f,
	0xbc, 0xcf, 0xfe, 0x56, 0x32, 0x4a, 0xbe, 0xfa, 0xfb, 0x2b, 0x35, 0x32, 0x1e, 0xe8, 0x2a, 0xfe,
	0x61, 0xe3, 0x63, 0x83, 0x8f, 0xaf, 0xe2, 0xc9, 0x2d, 0xed, 0xf0, 0xe4, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xb6, 0xb9, 0x71, 0xae, 0xab, 0x05, 0x00, 0x00,
}
