// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/account/v1/api_email.proto

package v1

import (
	fmt "fmt"
	v1 "github.com/AlpacaLabs/protorepo-pagination-go/alpacalabs/pagination/v1"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetEmailAddressesRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEmailAddressesRequest) Reset()         { *m = GetEmailAddressesRequest{} }
func (m *GetEmailAddressesRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesRequest) ProtoMessage()    {}
func (*GetEmailAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{0}
}

func (m *GetEmailAddressesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesRequest.Unmarshal(m, b)
}
func (m *GetEmailAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesRequest.Merge(m, src)
}
func (m *GetEmailAddressesRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesRequest.Size(m)
}
func (m *GetEmailAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesRequest proto.InternalMessageInfo

func (m *GetEmailAddressesRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

type GetEmailAddressesResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	EmailAddresses       []*EmailAddress    `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetEmailAddressesResponse) Reset()         { *m = GetEmailAddressesResponse{} }
func (m *GetEmailAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesResponse) ProtoMessage()    {}
func (*GetEmailAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{1}
}

func (m *GetEmailAddressesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesResponse.Unmarshal(m, b)
}
func (m *GetEmailAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesResponse.Merge(m, src)
}
func (m *GetEmailAddressesResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesResponse.Size(m)
}
func (m *GetEmailAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesResponse proto.InternalMessageInfo

func (m *GetEmailAddressesResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetEmailAddressesResponse) GetEmailAddresses() []*EmailAddress {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

type GetEmailAddressRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEmailAddressRequest) Reset()         { *m = GetEmailAddressRequest{} }
func (m *GetEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressRequest) ProtoMessage()    {}
func (*GetEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{2}
}

func (m *GetEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressRequest.Unmarshal(m, b)
}
func (m *GetEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressRequest.Merge(m, src)
}
func (m *GetEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressRequest.Size(m)
}
func (m *GetEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressRequest proto.InternalMessageInfo

func (m *GetEmailAddressRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetEmailAddressResponse struct {
	EmailAddress         *EmailAddress `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetEmailAddressResponse) Reset()         { *m = GetEmailAddressResponse{} }
func (m *GetEmailAddressResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressResponse) ProtoMessage()    {}
func (*GetEmailAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{3}
}

func (m *GetEmailAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressResponse.Unmarshal(m, b)
}
func (m *GetEmailAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressResponse.Merge(m, src)
}
func (m *GetEmailAddressResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressResponse.Size(m)
}
func (m *GetEmailAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressResponse proto.InternalMessageInfo

func (m *GetEmailAddressResponse) GetEmailAddress() *EmailAddress {
	if m != nil {
		return m.EmailAddress
	}
	return nil
}

type RegisterEmailAddressRequest struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterEmailAddressRequest) Reset()         { *m = RegisterEmailAddressRequest{} }
func (m *RegisterEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterEmailAddressRequest) ProtoMessage()    {}
func (*RegisterEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{4}
}

func (m *RegisterEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterEmailAddressRequest.Unmarshal(m, b)
}
func (m *RegisterEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *RegisterEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterEmailAddressRequest.Merge(m, src)
}
func (m *RegisterEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterEmailAddressRequest.Size(m)
}
func (m *RegisterEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterEmailAddressRequest proto.InternalMessageInfo

func (m *RegisterEmailAddressRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *RegisterEmailAddressRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type RegisterEmailAddressResponse struct {
	EmailAddress         *EmailAddress `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RegisterEmailAddressResponse) Reset()         { *m = RegisterEmailAddressResponse{} }
func (m *RegisterEmailAddressResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterEmailAddressResponse) ProtoMessage()    {}
func (*RegisterEmailAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{5}
}

func (m *RegisterEmailAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterEmailAddressResponse.Unmarshal(m, b)
}
func (m *RegisterEmailAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterEmailAddressResponse.Marshal(b, m, deterministic)
}
func (m *RegisterEmailAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterEmailAddressResponse.Merge(m, src)
}
func (m *RegisterEmailAddressResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterEmailAddressResponse.Size(m)
}
func (m *RegisterEmailAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterEmailAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterEmailAddressResponse proto.InternalMessageInfo

func (m *RegisterEmailAddressResponse) GetEmailAddress() *EmailAddress {
	if m != nil {
		return m.EmailAddress
	}
	return nil
}

type UnregisterEmailAddressRequest struct {
	EmailAddressId       string   `protobuf:"bytes,1,opt,name=email_address_id,json=emailAddressId,proto3" json:"email_address_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterEmailAddressRequest) Reset()         { *m = UnregisterEmailAddressRequest{} }
func (m *UnregisterEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterEmailAddressRequest) ProtoMessage()    {}
func (*UnregisterEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{6}
}

func (m *UnregisterEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterEmailAddressRequest.Unmarshal(m, b)
}
func (m *UnregisterEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterEmailAddressRequest.Merge(m, src)
}
func (m *UnregisterEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterEmailAddressRequest.Size(m)
}
func (m *UnregisterEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterEmailAddressRequest proto.InternalMessageInfo

func (m *UnregisterEmailAddressRequest) GetEmailAddressId() string {
	if m != nil {
		return m.EmailAddressId
	}
	return ""
}

type UnregisterEmailAddressResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterEmailAddressResponse) Reset()         { *m = UnregisterEmailAddressResponse{} }
func (m *UnregisterEmailAddressResponse) String() string { return proto.CompactTextString(m) }
func (*UnregisterEmailAddressResponse) ProtoMessage()    {}
func (*UnregisterEmailAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{7}
}

func (m *UnregisterEmailAddressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterEmailAddressResponse.Unmarshal(m, b)
}
func (m *UnregisterEmailAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterEmailAddressResponse.Marshal(b, m, deterministic)
}
func (m *UnregisterEmailAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterEmailAddressResponse.Merge(m, src)
}
func (m *UnregisterEmailAddressResponse) XXX_Size() int {
	return xxx_messageInfo_UnregisterEmailAddressResponse.Size(m)
}
func (m *UnregisterEmailAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterEmailAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterEmailAddressResponse proto.InternalMessageInfo

type ConfirmEmailAddressRequest struct {
	EmailAddressId       string   `protobuf:"bytes,1,opt,name=email_address_id,json=emailAddressId,proto3" json:"email_address_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailAddressRequest) Reset()         { *m = ConfirmEmailAddressRequest{} }
func (m *ConfirmEmailAddressRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailAddressRequest) ProtoMessage()    {}
func (*ConfirmEmailAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{8}
}

func (m *ConfirmEmailAddressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Unmarshal(m, b)
}
func (m *ConfirmEmailAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailAddressRequest.Merge(m, src)
}
func (m *ConfirmEmailAddressRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailAddressRequest.Size(m)
}
func (m *ConfirmEmailAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailAddressRequest proto.InternalMessageInfo

func (m *ConfirmEmailAddressRequest) GetEmailAddressId() string {
	if m != nil {
		return m.EmailAddressId
	}
	return ""
}

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetEmailAddressesForAccountIDRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	AccountId            string            `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetEmailAddressesForAccountIDRequest) Reset()         { *m = GetEmailAddressesForAccountIDRequest{} }
func (m *GetEmailAddressesForAccountIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesForAccountIDRequest) ProtoMessage()    {}
func (*GetEmailAddressesForAccountIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{9}
}

func (m *GetEmailAddressesForAccountIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Unmarshal(m, b)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Merge(m, src)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesForAccountIDRequest.Size(m)
}
func (m *GetEmailAddressesForAccountIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesForAccountIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesForAccountIDRequest proto.InternalMessageInfo

func (m *GetEmailAddressesForAccountIDRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

func (m *GetEmailAddressesForAccountIDRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetEmailAddressesForAccountIDResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	EmailAddresses       []*EmailAddress    `protobuf:"bytes,2,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetEmailAddressesForAccountIDResponse) Reset()         { *m = GetEmailAddressesForAccountIDResponse{} }
func (m *GetEmailAddressesForAccountIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetEmailAddressesForAccountIDResponse) ProtoMessage()    {}
func (*GetEmailAddressesForAccountIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b7338160ae739ad, []int{10}
}

func (m *GetEmailAddressesForAccountIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Unmarshal(m, b)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Marshal(b, m, deterministic)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Merge(m, src)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetEmailAddressesForAccountIDResponse.Size(m)
}
func (m *GetEmailAddressesForAccountIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmailAddressesForAccountIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmailAddressesForAccountIDResponse proto.InternalMessageInfo

func (m *GetEmailAddressesForAccountIDResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetEmailAddressesForAccountIDResponse) GetEmailAddresses() []*EmailAddress {
	if m != nil {
		return m.EmailAddresses
	}
	return nil
}

func init() {
	proto.RegisterType((*GetEmailAddressesRequest)(nil), "alpacalabs.account.v1.GetEmailAddressesRequest")
	proto.RegisterType((*GetEmailAddressesResponse)(nil), "alpacalabs.account.v1.GetEmailAddressesResponse")
	proto.RegisterType((*GetEmailAddressRequest)(nil), "alpacalabs.account.v1.GetEmailAddressRequest")
	proto.RegisterType((*GetEmailAddressResponse)(nil), "alpacalabs.account.v1.GetEmailAddressResponse")
	proto.RegisterType((*RegisterEmailAddressRequest)(nil), "alpacalabs.account.v1.RegisterEmailAddressRequest")
	proto.RegisterType((*RegisterEmailAddressResponse)(nil), "alpacalabs.account.v1.RegisterEmailAddressResponse")
	proto.RegisterType((*UnregisterEmailAddressRequest)(nil), "alpacalabs.account.v1.UnregisterEmailAddressRequest")
	proto.RegisterType((*UnregisterEmailAddressResponse)(nil), "alpacalabs.account.v1.UnregisterEmailAddressResponse")
	proto.RegisterType((*ConfirmEmailAddressRequest)(nil), "alpacalabs.account.v1.ConfirmEmailAddressRequest")
	proto.RegisterType((*GetEmailAddressesForAccountIDRequest)(nil), "alpacalabs.account.v1.GetEmailAddressesForAccountIDRequest")
	proto.RegisterType((*GetEmailAddressesForAccountIDResponse)(nil), "alpacalabs.account.v1.GetEmailAddressesForAccountIDResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/account/v1/api_email.proto", fileDescriptor_5b7338160ae739ad)
}

var fileDescriptor_5b7338160ae739ad = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x94, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x95, 0x4c, 0x42, 0xea, 0xd9, 0xd6, 0xa1, 0x48, 0x83, 0xae, 0x30, 0x54, 0x5c, 0x26,
	0x72, 0x33, 0x47, 0x19, 0x2f, 0x40, 0x36, 0x18, 0x54, 0xaa, 0xd0, 0x88, 0xc4, 0x2e, 0xd0, 0xa4,
	0xc8, 0x75, 0x4c, 0x66, 0xd4, 0xc4, 0xc1, 0x4e, 0xfa, 0x26, 0xbc, 0x00, 0xdc, 0xf1, 0x0c, 0x3c,
	0x00, 0xe2, 0xa9, 0x50, 0x12, 0x6f, 0x4d, 0xa8, 0xa1, 0x48, 0xc0, 0xc5, 0x2e, 0x7d, 0x72, 0xfe,
	0xf3, 0xfd, 0xe7, 0x38, 0x3e, 0x70, 0x40, 0xe6, 0x39, 0xa1, 0x64, 0x4e, 0x66, 0xca, 0x23, 0x94,
	0x8a, 0x32, 0x2b, 0xbc, 0x85, 0xef, 0x91, 0x9c, 0x47, 0x2c, 0x25, 0x7c, 0x8e, 0x73, 0x29, 0x0a,
	0xe1, 0xec, 0x2e, 0xd3, 0xb0, 0x4e, 0xc3, 0x0b, 0x7f, 0x38, 0x6e, 0xa9, 0x73, 0x92, 0xf0, 0x8c,
	0x14, 0x5c, 0x64, 0x55, 0x81, 0x9c, 0x24, 0xac, 0xd1, 0x0e, 0x1f, 0x9a, 0x11, 0xad, 0xf2, 0xe8,
	0x3d, 0x0c, 0x5e, 0xb0, 0xe2, 0x79, 0x15, 0x09, 0xe2, 0x58, 0x32, 0xa5, 0x98, 0x0a, 0xd9, 0x87,
	0x92, 0xa9, 0xc2, 0x79, 0x05, 0x7d, 0x5a, 0x4a, 0x25, 0x64, 0x24, 0x9b, 0xc8, 0xc0, 0x1a, 0x59,
	0xee, 0xe6, 0xd1, 0x63, 0xdc, 0xf2, 0xb4, 0x84, 0xe3, 0x85, 0x8f, 0x4f, 0xea, 0x7c, 0x5d, 0x20,
	0xdc, 0xa6, 0xed, 0x23, 0xfa, 0x6a, 0xc1, 0x9e, 0x01, 0xa6, 0x72, 0x91, 0x29, 0xe6, 0xbc, 0x86,
	0x9d, 0x6b, 0x5a, 0x13, 0xd2, 0x38, 0x77, 0x3d, 0xae, 0xc9, 0x0f, 0xfb, 0xb4, 0x73, 0x76, 0xa6,
	0xb0, 0x53, 0xf7, 0x1a, 0x91, 0x2b, 0xda, 0xc0, 0x1e, 0x6d, 0xb8, 0x9b, 0x47, 0x63, 0x6c, 0x9c,
	0x2a, 0x6e, 0x5b, 0x0b, 0xfb, 0xac, 0x63, 0x14, 0xb9, 0x70, 0xe7, 0x27, 0xf7, 0x57, 0x83, 0xea,
	0x83, 0xcd, 0xe3, 0xda, 0x6d, 0x2f, 0xb4, 0x79, 0x8c, 0x28, 0xdc, 0x5d, 0xc9, 0xd4, 0x96, 0x5e,
	0xc2, 0x76, 0xc7, 0x92, 0xee, 0xf1, 0x8f, 0x0c, 0x6d, 0xb5, 0x0d, 0x21, 0x02, 0xf7, 0x42, 0x96,
	0x70, 0x55, 0x30, 0x69, 0xf2, 0x34, 0x36, 0x81, 0x7a, 0xdd, 0x1a, 0xce, 0x3e, 0x80, 0x86, 0x45,
	0x3c, 0x1e, 0xd8, 0x75, 0x46, 0x4f, 0x47, 0x26, 0x31, 0xba, 0x84, 0xfb, 0x66, 0xc4, 0x3f, 0x6f,
	0x66, 0x02, 0xfb, 0x6f, 0x32, 0xf9, 0x9b, 0x76, 0x5c, 0xb8, 0xdd, 0x41, 0x45, 0xd7, 0x03, 0xef,
	0x5c, 0xd3, 0x24, 0x46, 0x23, 0x78, 0xf0, 0xab, 0x52, 0x8d, 0x6d, 0x74, 0x0a, 0xc3, 0x13, 0x91,
	0xbd, 0xe3, 0x32, 0xfd, 0x3b, 0xd2, 0x47, 0x0b, 0x1e, 0xad, 0xfc, 0xcf, 0xa7, 0x42, 0x06, 0x7a,
	0x80, 0xcf, 0xfe, 0xd3, 0x43, 0x5a, 0x77, 0x6d, 0xdf, 0x2c, 0x38, 0x58, 0xe3, 0xeb, 0x86, 0xbc,
	0xb9, 0xe3, 0xcf, 0x16, 0xec, 0x51, 0x91, 0x9a, 0xa5, 0xc7, 0x5b, 0xba, 0xa3, 0xb3, 0x6a, 0x95,
	0x9d, 0x59, 0x6f, 0x9f, 0x26, 0xbc, 0xb8, 0x2c, 0x67, 0x98, 0x8a, 0xd4, 0x0b, 0x6a, 0xc5, 0xb4,
	0xde, 0x8f, 0xd5, 0x67, 0xc9, 0x72, 0x71, 0xa8, 0xb5, 0x87, 0x89, 0xf0, 0x8c, 0xab, 0xf1, 0x93,
	0xbd, 0x11, 0x4c, 0x83, 0x2f, 0xf6, 0xee, 0x52, 0x8d, 0x35, 0x03, 0x9f, 0xfb, 0xdf, 0xdb, 0xf1,
	0x0b, 0x1d, 0xbf, 0x38, 0xf7, 0x67, 0xb7, 0x6a, 0xc2, 0x93, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xb8, 0x48, 0xc4, 0x00, 0xd3, 0x05, 0x00, 0x00,
}
