// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/account/v1/api_phone_number.proto

package v1

import (
	fmt "fmt"
	v1 "github.com/AlpacaLabs/protorepo-pagination-go/alpacalabs/pagination/v1"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetPhoneNumbersRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetPhoneNumbersRequest) Reset()         { *m = GetPhoneNumbersRequest{} }
func (m *GetPhoneNumbersRequest) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumbersRequest) ProtoMessage()    {}
func (*GetPhoneNumbersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{0}
}

func (m *GetPhoneNumbersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumbersRequest.Unmarshal(m, b)
}
func (m *GetPhoneNumbersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumbersRequest.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumbersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumbersRequest.Merge(m, src)
}
func (m *GetPhoneNumbersRequest) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumbersRequest.Size(m)
}
func (m *GetPhoneNumbersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumbersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumbersRequest proto.InternalMessageInfo

func (m *GetPhoneNumbersRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

type GetPhoneNumbersResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	PhoneNumbers         []*PhoneNumber     `protobuf:"bytes,2,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetPhoneNumbersResponse) Reset()         { *m = GetPhoneNumbersResponse{} }
func (m *GetPhoneNumbersResponse) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumbersResponse) ProtoMessage()    {}
func (*GetPhoneNumbersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{1}
}

func (m *GetPhoneNumbersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumbersResponse.Unmarshal(m, b)
}
func (m *GetPhoneNumbersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumbersResponse.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumbersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumbersResponse.Merge(m, src)
}
func (m *GetPhoneNumbersResponse) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumbersResponse.Size(m)
}
func (m *GetPhoneNumbersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumbersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumbersResponse proto.InternalMessageInfo

func (m *GetPhoneNumbersResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetPhoneNumbersResponse) GetPhoneNumbers() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

type GetPhoneNumberByIDRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPhoneNumberByIDRequest) Reset()         { *m = GetPhoneNumberByIDRequest{} }
func (m *GetPhoneNumberByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumberByIDRequest) ProtoMessage()    {}
func (*GetPhoneNumberByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{2}
}

func (m *GetPhoneNumberByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumberByIDRequest.Unmarshal(m, b)
}
func (m *GetPhoneNumberByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumberByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumberByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumberByIDRequest.Merge(m, src)
}
func (m *GetPhoneNumberByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumberByIDRequest.Size(m)
}
func (m *GetPhoneNumberByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumberByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumberByIDRequest proto.InternalMessageInfo

func (m *GetPhoneNumberByIDRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPhoneNumberByIDResponse struct {
	PhoneNumber          *PhoneNumber `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPhoneNumberByIDResponse) Reset()         { *m = GetPhoneNumberByIDResponse{} }
func (m *GetPhoneNumberByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumberByIDResponse) ProtoMessage()    {}
func (*GetPhoneNumberByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{3}
}

func (m *GetPhoneNumberByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumberByIDResponse.Unmarshal(m, b)
}
func (m *GetPhoneNumberByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumberByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumberByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumberByIDResponse.Merge(m, src)
}
func (m *GetPhoneNumberByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumberByIDResponse.Size(m)
}
func (m *GetPhoneNumberByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumberByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumberByIDResponse proto.InternalMessageInfo

func (m *GetPhoneNumberByIDResponse) GetPhoneNumber() *PhoneNumber {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

type AddPhoneNumberRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPhoneNumberRequest) Reset()         { *m = AddPhoneNumberRequest{} }
func (m *AddPhoneNumberRequest) String() string { return proto.CompactTextString(m) }
func (*AddPhoneNumberRequest) ProtoMessage()    {}
func (*AddPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{4}
}

func (m *AddPhoneNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPhoneNumberRequest.Unmarshal(m, b)
}
func (m *AddPhoneNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPhoneNumberRequest.Marshal(b, m, deterministic)
}
func (m *AddPhoneNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPhoneNumberRequest.Merge(m, src)
}
func (m *AddPhoneNumberRequest) XXX_Size() int {
	return xxx_messageInfo_AddPhoneNumberRequest.Size(m)
}
func (m *AddPhoneNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPhoneNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPhoneNumberRequest proto.InternalMessageInfo

func (m *AddPhoneNumberRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *AddPhoneNumberRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type AddPhoneNumberResponse struct {
	PhoneNumber          *PhoneNumber `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddPhoneNumberResponse) Reset()         { *m = AddPhoneNumberResponse{} }
func (m *AddPhoneNumberResponse) String() string { return proto.CompactTextString(m) }
func (*AddPhoneNumberResponse) ProtoMessage()    {}
func (*AddPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{5}
}

func (m *AddPhoneNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPhoneNumberResponse.Unmarshal(m, b)
}
func (m *AddPhoneNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPhoneNumberResponse.Marshal(b, m, deterministic)
}
func (m *AddPhoneNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPhoneNumberResponse.Merge(m, src)
}
func (m *AddPhoneNumberResponse) XXX_Size() int {
	return xxx_messageInfo_AddPhoneNumberResponse.Size(m)
}
func (m *AddPhoneNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPhoneNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPhoneNumberResponse proto.InternalMessageInfo

func (m *AddPhoneNumberResponse) GetPhoneNumber() *PhoneNumber {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

type ConfirmPhoneNumberRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ConfirmationCode     string   `protobuf:"bytes,2,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPhoneNumberRequest) Reset()         { *m = ConfirmPhoneNumberRequest{} }
func (m *ConfirmPhoneNumberRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmPhoneNumberRequest) ProtoMessage()    {}
func (*ConfirmPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{6}
}

func (m *ConfirmPhoneNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Unmarshal(m, b)
}
func (m *ConfirmPhoneNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmPhoneNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPhoneNumberRequest.Merge(m, src)
}
func (m *ConfirmPhoneNumberRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmPhoneNumberRequest.Size(m)
}
func (m *ConfirmPhoneNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPhoneNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPhoneNumberRequest proto.InternalMessageInfo

func (m *ConfirmPhoneNumberRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *ConfirmPhoneNumberRequest) GetConfirmationCode() string {
	if m != nil {
		return m.ConfirmationCode
	}
	return ""
}

type ConfirmPhoneNumberResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmPhoneNumberResponse) Reset()         { *m = ConfirmPhoneNumberResponse{} }
func (m *ConfirmPhoneNumberResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmPhoneNumberResponse) ProtoMessage()    {}
func (*ConfirmPhoneNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{7}
}

func (m *ConfirmPhoneNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Unmarshal(m, b)
}
func (m *ConfirmPhoneNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmPhoneNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmPhoneNumberResponse.Merge(m, src)
}
func (m *ConfirmPhoneNumberResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmPhoneNumberResponse.Size(m)
}
func (m *ConfirmPhoneNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmPhoneNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmPhoneNumberResponse proto.InternalMessageInfo

// a request to get all email addresses in the system.
// this should be an admin-only ability.
type GetPhoneNumbersForAccountIDRequest struct {
	CursorRequest        *v1.CursorRequest `protobuf:"bytes,1,opt,name=cursor_request,json=cursorRequest,proto3" json:"cursor_request,omitempty"`
	AccountId            string            `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetPhoneNumbersForAccountIDRequest) Reset()         { *m = GetPhoneNumbersForAccountIDRequest{} }
func (m *GetPhoneNumbersForAccountIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumbersForAccountIDRequest) ProtoMessage()    {}
func (*GetPhoneNumbersForAccountIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{8}
}

func (m *GetPhoneNumbersForAccountIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDRequest.Unmarshal(m, b)
}
func (m *GetPhoneNumbersForAccountIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDRequest.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumbersForAccountIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumbersForAccountIDRequest.Merge(m, src)
}
func (m *GetPhoneNumbersForAccountIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDRequest.Size(m)
}
func (m *GetPhoneNumbersForAccountIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumbersForAccountIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumbersForAccountIDRequest proto.InternalMessageInfo

func (m *GetPhoneNumbersForAccountIDRequest) GetCursorRequest() *v1.CursorRequest {
	if m != nil {
		return m.CursorRequest
	}
	return nil
}

func (m *GetPhoneNumbersForAccountIDRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type GetPhoneNumbersForAccountIDResponse struct {
	CursorResponse       *v1.CursorResponse `protobuf:"bytes,1,opt,name=cursor_response,json=cursorResponse,proto3" json:"cursor_response,omitempty"`
	PhoneNumbers         []*PhoneNumber     `protobuf:"bytes,2,rep,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetPhoneNumbersForAccountIDResponse) Reset()         { *m = GetPhoneNumbersForAccountIDResponse{} }
func (m *GetPhoneNumbersForAccountIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetPhoneNumbersForAccountIDResponse) ProtoMessage()    {}
func (*GetPhoneNumbersForAccountIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b91d3d7e8a819384, []int{9}
}

func (m *GetPhoneNumbersForAccountIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDResponse.Unmarshal(m, b)
}
func (m *GetPhoneNumbersForAccountIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDResponse.Marshal(b, m, deterministic)
}
func (m *GetPhoneNumbersForAccountIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPhoneNumbersForAccountIDResponse.Merge(m, src)
}
func (m *GetPhoneNumbersForAccountIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetPhoneNumbersForAccountIDResponse.Size(m)
}
func (m *GetPhoneNumbersForAccountIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPhoneNumbersForAccountIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPhoneNumbersForAccountIDResponse proto.InternalMessageInfo

func (m *GetPhoneNumbersForAccountIDResponse) GetCursorResponse() *v1.CursorResponse {
	if m != nil {
		return m.CursorResponse
	}
	return nil
}

func (m *GetPhoneNumbersForAccountIDResponse) GetPhoneNumbers() []*PhoneNumber {
	if m != nil {
		return m.PhoneNumbers
	}
	return nil
}

func init() {
	proto.RegisterType((*GetPhoneNumbersRequest)(nil), "alpacalabs.account.v1.GetPhoneNumbersRequest")
	proto.RegisterType((*GetPhoneNumbersResponse)(nil), "alpacalabs.account.v1.GetPhoneNumbersResponse")
	proto.RegisterType((*GetPhoneNumberByIDRequest)(nil), "alpacalabs.account.v1.GetPhoneNumberByIDRequest")
	proto.RegisterType((*GetPhoneNumberByIDResponse)(nil), "alpacalabs.account.v1.GetPhoneNumberByIDResponse")
	proto.RegisterType((*AddPhoneNumberRequest)(nil), "alpacalabs.account.v1.AddPhoneNumberRequest")
	proto.RegisterType((*AddPhoneNumberResponse)(nil), "alpacalabs.account.v1.AddPhoneNumberResponse")
	proto.RegisterType((*ConfirmPhoneNumberRequest)(nil), "alpacalabs.account.v1.ConfirmPhoneNumberRequest")
	proto.RegisterType((*ConfirmPhoneNumberResponse)(nil), "alpacalabs.account.v1.ConfirmPhoneNumberResponse")
	proto.RegisterType((*GetPhoneNumbersForAccountIDRequest)(nil), "alpacalabs.account.v1.GetPhoneNumbersForAccountIDRequest")
	proto.RegisterType((*GetPhoneNumbersForAccountIDResponse)(nil), "alpacalabs.account.v1.GetPhoneNumbersForAccountIDResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/account/v1/api_phone_number.proto", fileDescriptor_b91d3d7e8a819384)
}

var fileDescriptor_b91d3d7e8a819384 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0xd1, 0x6a, 0x13, 0x41,
	0x14, 0x86, 0xd9, 0x2d, 0x08, 0x39, 0x49, 0xa3, 0x2e, 0xa4, 0x26, 0x41, 0xa1, 0x4e, 0x2f, 0x0c,
	0xd4, 0xce, 0xb2, 0xf5, 0x05, 0xdc, 0xa4, 0x5a, 0x0a, 0xa5, 0xc4, 0xbd, 0x28, 0x28, 0x85, 0x65,
	0x32, 0x33, 0x26, 0x83, 0xcd, 0xce, 0x38, 0xbb, 0x1b, 0xf0, 0x39, 0x7c, 0x03, 0xbd, 0xf3, 0xde,
	0x07, 0xf0, 0xd6, 0xa7, 0x92, 0x9d, 0x1d, 0xcd, 0xa4, 0x5d, 0xac, 0x88, 0x42, 0x2f, 0xf7, 0x9c,
	0xf3, 0x9f, 0xff, 0x3b, 0xb3, 0x33, 0x07, 0x9e, 0x92, 0x4b, 0x45, 0x28, 0xb9, 0x24, 0xb3, 0x3c,
	0x24, 0x94, 0xca, 0x32, 0x2b, 0xc2, 0x55, 0x14, 0x12, 0x25, 0x52, 0xb5, 0x90, 0x19, 0x4f, 0xb3,
	0x72, 0x39, 0xe3, 0x1a, 0x2b, 0x2d, 0x0b, 0x19, 0xf4, 0xd6, 0xd5, 0xd8, 0x56, 0xe3, 0x55, 0x34,
	0xdc, 0x73, 0x9a, 0x28, 0x32, 0x17, 0x19, 0x29, 0x84, 0xcc, 0xaa, 0x3e, 0x8a, 0xcc, 0x79, 0xad,
	0x1d, 0x8e, 0x9a, 0x9d, 0xae, 0xbb, 0xa0, 0x05, 0xec, 0x1c, 0xf3, 0x62, 0x5a, 0x25, 0xce, 0x4c,
	0x3c, 0x4f, 0xf8, 0xfb, 0x92, 0xe7, 0x45, 0x70, 0x06, 0x5d, 0x5a, 0xea, 0x5c, 0xea, 0x54, 0xd7,
	0x91, 0xbe, 0xb7, 0xeb, 0x8d, 0xda, 0x87, 0x4f, 0xb0, 0x03, 0xb6, 0x26, 0xc0, 0xab, 0x08, 0x4f,
	0x4c, 0xbd, 0x6d, 0x90, 0x6c, 0x53, 0xf7, 0x13, 0x7d, 0xf5, 0xe0, 0xc1, 0x35, 0xab, 0x5c, 0xc9,
	0x2c, 0xe7, 0xc1, 0x2b, 0xb8, 0xfb, 0xcb, 0xab, 0x0e, 0x59, 0xb3, 0xd1, 0xcd, 0x66, 0x75, 0x7d,
	0xd2, 0xa5, 0x1b, 0xdf, 0xc1, 0x31, 0x6c, 0xbb, 0xe3, 0xe6, 0x7d, 0x7f, 0x77, 0x6b, 0xd4, 0x3e,
	0x44, 0xb8, 0xf1, 0x58, 0xb1, 0x83, 0x95, 0x74, 0x94, 0xc3, 0x88, 0xf6, 0x61, 0xb0, 0x89, 0x3d,
	0xfe, 0x70, 0x72, 0xf4, 0xf3, 0x90, 0xba, 0xe0, 0x0b, 0x66, 0x58, 0x5b, 0x89, 0x2f, 0x18, 0xa2,
	0x30, 0x6c, 0x2a, 0xb6, 0x4c, 0x2f, 0xa0, 0xe3, 0x32, 0xd9, 0x19, 0xff, 0x04, 0xa9, 0xed, 0x20,
	0xa1, 0xd7, 0xd0, 0x8b, 0x19, 0x73, 0xd3, 0x96, 0xe6, 0x71, 0x43, 0xff, 0xd6, 0x86, 0x36, 0x78,
	0x04, 0x60, 0x2d, 0x52, 0xc1, 0xfa, 0xbe, 0x29, 0x68, 0xd9, 0xc8, 0x09, 0x43, 0x29, 0xec, 0x5c,
	0x6d, 0xfd, 0x6f, 0xd9, 0xdf, 0xc1, 0x60, 0x22, 0xb3, 0xb7, 0x42, 0x2f, 0xff, 0x8e, 0x7f, 0x1f,
	0xee, 0xd3, 0x5a, 0x6f, 0x2e, 0x42, 0x4a, 0x25, 0xe3, 0x76, 0x8c, 0x7b, 0x6e, 0x62, 0x22, 0x19,
	0x47, 0x0f, 0x61, 0xd8, 0x64, 0x56, 0x4f, 0x84, 0x3e, 0x7a, 0x80, 0xae, 0x5c, 0xc8, 0x97, 0x52,
	0xc7, 0xf6, 0x2c, 0x8e, 0xfe, 0xd3, 0x3b, 0xb8, 0xe9, 0x0f, 0x7c, 0xf3, 0x60, 0xef, 0xb7, 0x54,
	0xb7, 0xff, 0xc9, 0x8c, 0x3f, 0x7b, 0x30, 0xa0, 0x72, 0xd9, 0xac, 0x1b, 0x77, 0xec, 0x30, 0xd3,
	0x6a, 0x01, 0x4d, 0xbd, 0x37, 0xcf, 0xe7, 0xa2, 0x58, 0x94, 0x33, 0x4c, 0xe5, 0x32, 0x8c, 0x8d,
	0xe2, 0xd4, 0x2c, 0xb7, 0x2a, 0xad, 0xb9, 0x92, 0x07, 0x56, 0x7b, 0x30, 0x97, 0x61, 0xe3, 0x5e,
	0xfb, 0xe4, 0x6f, 0xc5, 0xa7, 0xf1, 0x17, 0xbf, 0xb7, 0x56, 0x63, 0xeb, 0x81, 0xcf, 0xa3, 0xef,
	0x6e, 0xfc, 0xc2, 0xc6, 0x2f, 0xce, 0xa3, 0xd9, 0x1d, 0xe3, 0xf0, 0xec, 0x47, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x0f, 0xba, 0x2b, 0x9b, 0x97, 0x05, 0x00, 0x00,
}
