// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/account/v1/api_account.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccountRequest struct {
	// required
	EmailAddress string `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	// optional
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// optional
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097f6a424720a1c4, []int{0}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *CreateAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateAccountRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097f6a424720a1c4, []int{1}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateAccountRequest)(nil), "alpacalabs.account.v1.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "alpacalabs.account.v1.CreateAccountResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/account/v1/api_account.proto", fileDescriptor_097f6a424720a1c4)
}

var fileDescriptor_097f6a424720a1c4 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcb, 0x4e, 0xc2, 0x40,
	0x14, 0x86, 0x53, 0x48, 0xbc, 0x0c, 0x75, 0xd3, 0xd8, 0xa4, 0xb2, 0x30, 0x0a, 0x0b, 0xdd, 0x30,
	0x4d, 0x75, 0xe3, 0xd2, 0xe2, 0x96, 0x18, 0x64, 0xc1, 0xc2, 0x90, 0x34, 0xa7, 0xe5, 0x04, 0x9a,
	0xb4, 0x33, 0xe3, 0x5c, 0x58, 0xf8, 0x38, 0xba, 0xf3, 0x51, 0x7c, 0x2a, 0xc3, 0x30, 0x15, 0x62,
	0xea, 0xf2, 0x7c, 0xe7, 0xff, 0x72, 0x2e, 0xe4, 0x06, 0x2a, 0x01, 0x05, 0x54, 0x90, 0xab, 0x18,
	0x8a, 0x82, 0x1b, 0xa6, 0xe3, 0x4d, 0x12, 0x83, 0x28, 0x33, 0x57, 0x52, 0x21, 0xb9, 0xe6, 0x41,
	0xb8, 0x0f, 0xd2, 0xa6, 0xb3, 0x49, 0xfa, 0xc3, 0x7f, 0xfc, 0x43, 0x77, 0xf0, 0x4e, 0xce, 0x9f,
	0x24, 0x82, 0xc6, 0x74, 0x87, 0x67, 0xf8, 0x66, 0x50, 0xe9, 0x60, 0x48, 0xce, 0xb0, 0x86, 0xb2,
	0xca, 0x60, 0xb9, 0x94, 0xa8, 0x54, 0xe4, 0x5d, 0x79, 0xb7, 0xa7, 0x33, 0xdf, 0xc2, 0x74, 0xc7,
	0x82, 0x3e, 0x39, 0x31, 0x0a, 0x25, 0x83, 0x1a, 0xa3, 0x8e, 0xed, 0xff, 0xd6, 0xc1, 0x35, 0xf1,
	0xc5, 0x9a, 0x33, 0xcc, 0x98, 0xa9, 0x73, 0x94, 0x51, 0xd7, 0xf6, 0x7b, 0x96, 0x3d, 0x5b, 0x34,
	0x78, 0x21, 0xe1, 0x9f, 0xd9, 0x4a, 0x70, 0xa6, 0x30, 0x78, 0x20, 0xc7, 0x6e, 0x4b, 0x3b, 0xb6,
	0x77, 0x77, 0x49, 0x5b, 0x4f, 0xa4, 0x8d, 0xd8, 0xc4, 0xc7, 0x9f, 0x1e, 0xb9, 0x28, 0x78, 0xdd,
	0x1e, 0x1f, 0xfb, 0x2e, 0x3f, 0xdd, 0x9e, 0x3e, 0xf5, 0x5e, 0x1f, 0x57, 0xa5, 0x5e, 0x9b, 0x9c,
	0x16, 0xbc, 0x8e, 0x53, 0x6b, 0x4c, 0xb6, 0xcf, 0xb2, 0x9f, 0x91, 0x28, 0xf8, 0xc8, 0xb9, 0xa3,
	0x15, 0x8f, 0x5b, 0x9f, 0xf9, 0xd1, 0xe9, 0xa6, 0x93, 0xf4, 0xab, 0x13, 0xee, 0xed, 0x66, 0x27,
	0x3a, 0x4f, 0xbe, 0x0f, 0xf9, 0xc2, 0xf1, 0xc5, 0x3c, 0xc9, 0x8f, 0xec, 0x84, 0xfb, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x7d, 0x1e, 0x73, 0x09, 0xe2, 0x01, 0x00, 0x00,
}
