// Code generated by protoc-gen-go. DO NOT EDIT.
// source: alpacalabs/account/v1/api_account.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateAccountRequest struct {
	// required
	EmailAddress string `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	// optional
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// optional
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097f6a424720a1c4, []int{0}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *CreateAccountRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateAccountRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

type CreateAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097f6a424720a1c4, []int{1}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type GetAccountRequest struct {
	// Types that are valid to be assigned to AccountIdentifier:
	//	*GetAccountRequest_AccountId
	//	*GetAccountRequest_EmailAddress
	//	*GetAccountRequest_EmailAddressId
	//	*GetAccountRequest_PhoneNumber
	//	*GetAccountRequest_PhoneNumberId
	//	*GetAccountRequest_Username
	AccountIdentifier    isGetAccountRequest_AccountIdentifier `protobuf_oneof:"account_identifier"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097f6a424720a1c4, []int{2}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

type isGetAccountRequest_AccountIdentifier interface {
	isGetAccountRequest_AccountIdentifier()
}

type GetAccountRequest_AccountId struct {
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3,oneof"`
}

type GetAccountRequest_EmailAddress struct {
	EmailAddress string `protobuf:"bytes,2,opt,name=email_address,json=emailAddress,proto3,oneof"`
}

type GetAccountRequest_EmailAddressId struct {
	EmailAddressId string `protobuf:"bytes,3,opt,name=email_address_id,json=emailAddressId,proto3,oneof"`
}

type GetAccountRequest_PhoneNumber struct {
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3,oneof"`
}

type GetAccountRequest_PhoneNumberId struct {
	PhoneNumberId string `protobuf:"bytes,5,opt,name=phone_number_id,json=phoneNumberId,proto3,oneof"`
}

type GetAccountRequest_Username struct {
	Username string `protobuf:"bytes,6,opt,name=username,proto3,oneof"`
}

func (*GetAccountRequest_AccountId) isGetAccountRequest_AccountIdentifier() {}

func (*GetAccountRequest_EmailAddress) isGetAccountRequest_AccountIdentifier() {}

func (*GetAccountRequest_EmailAddressId) isGetAccountRequest_AccountIdentifier() {}

func (*GetAccountRequest_PhoneNumber) isGetAccountRequest_AccountIdentifier() {}

func (*GetAccountRequest_PhoneNumberId) isGetAccountRequest_AccountIdentifier() {}

func (*GetAccountRequest_Username) isGetAccountRequest_AccountIdentifier() {}

func (m *GetAccountRequest) GetAccountIdentifier() isGetAccountRequest_AccountIdentifier {
	if m != nil {
		return m.AccountIdentifier
	}
	return nil
}

func (m *GetAccountRequest) GetAccountId() string {
	if x, ok := m.GetAccountIdentifier().(*GetAccountRequest_AccountId); ok {
		return x.AccountId
	}
	return ""
}

func (m *GetAccountRequest) GetEmailAddress() string {
	if x, ok := m.GetAccountIdentifier().(*GetAccountRequest_EmailAddress); ok {
		return x.EmailAddress
	}
	return ""
}

func (m *GetAccountRequest) GetEmailAddressId() string {
	if x, ok := m.GetAccountIdentifier().(*GetAccountRequest_EmailAddressId); ok {
		return x.EmailAddressId
	}
	return ""
}

func (m *GetAccountRequest) GetPhoneNumber() string {
	if x, ok := m.GetAccountIdentifier().(*GetAccountRequest_PhoneNumber); ok {
		return x.PhoneNumber
	}
	return ""
}

func (m *GetAccountRequest) GetPhoneNumberId() string {
	if x, ok := m.GetAccountIdentifier().(*GetAccountRequest_PhoneNumberId); ok {
		return x.PhoneNumberId
	}
	return ""
}

func (m *GetAccountRequest) GetUsername() string {
	if x, ok := m.GetAccountIdentifier().(*GetAccountRequest_Username); ok {
		return x.Username
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetAccountRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetAccountRequest_AccountId)(nil),
		(*GetAccountRequest_EmailAddress)(nil),
		(*GetAccountRequest_EmailAddressId)(nil),
		(*GetAccountRequest_PhoneNumber)(nil),
		(*GetAccountRequest_PhoneNumberId)(nil),
		(*GetAccountRequest_Username)(nil),
	}
}

type GetAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097f6a424720a1c4, []int{3}
}

func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateAccountRequest)(nil), "alpacalabs.account.v1.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "alpacalabs.account.v1.CreateAccountResponse")
	proto.RegisterType((*GetAccountRequest)(nil), "alpacalabs.account.v1.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "alpacalabs.account.v1.GetAccountResponse")
}

func init() {
	proto.RegisterFile("alpacalabs/account/v1/api_account.proto", fileDescriptor_097f6a424720a1c4)
}

var fileDescriptor_097f6a424720a1c4 = []byte{
	// 390 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0xc7, 0x6f, 0xcb, 0xbd, 0x5c, 0x19, 0xc0, 0x8f, 0x09, 0x24, 0x48, 0x8c, 0x1f, 0x25, 0x46,
	0x62, 0x42, 0x9b, 0xea, 0xc6, 0xa5, 0xc5, 0x85, 0x92, 0x10, 0x82, 0x2c, 0x58, 0x18, 0x92, 0x66,
	0xda, 0x1e, 0xa1, 0x09, 0xed, 0xd4, 0x7e, 0xb0, 0xf0, 0x11, 0x7c, 0x0c, 0xdd, 0xf9, 0x28, 0x3e,
	0x95, 0xe9, 0x30, 0x85, 0xa1, 0xc1, 0x95, 0xcb, 0xf9, 0x9f, 0xdf, 0x7f, 0xce, 0xf9, 0x9f, 0x1c,
	0x74, 0x41, 0xe6, 0x01, 0xb1, 0xc9, 0x9c, 0x58, 0x91, 0x46, 0x6c, 0x9b, 0x26, 0x7e, 0xac, 0x2d,
	0x74, 0x8d, 0x04, 0xae, 0xc9, 0x9f, 0x6a, 0x10, 0xd2, 0x98, 0xe2, 0xfa, 0x1a, 0x54, 0xb3, 0xca,
	0x42, 0x6f, 0xb6, 0x7e, 0xf0, 0x8b, 0x5e, 0xe5, 0x15, 0xd5, 0xee, 0x42, 0x20, 0x31, 0x18, 0x4b,
	0x79, 0x04, 0x2f, 0x09, 0x44, 0x31, 0x6e, 0xa1, 0x2a, 0x78, 0xc4, 0x9d, 0x9b, 0xc4, 0x71, 0x42,
	0x88, 0xa2, 0x86, 0x74, 0x2a, 0xb5, 0x4b, 0xa3, 0x0a, 0x13, 0x8d, 0xa5, 0x86, 0x9b, 0x68, 0x27,
	0x89, 0x20, 0xf4, 0x89, 0x07, 0x0d, 0x99, 0xd5, 0x57, 0x6f, 0x7c, 0x86, 0x2a, 0xc1, 0x8c, 0xfa,
	0x60, 0xfa, 0x89, 0x67, 0x41, 0xd8, 0x28, 0xb0, 0x7a, 0x99, 0x69, 0x03, 0x26, 0x29, 0x8f, 0xa8,
	0x9e, 0xeb, 0x1d, 0x05, 0xd4, 0x8f, 0x00, 0xdf, 0xa0, 0xff, 0x7c, 0x4a, 0xd6, 0xb6, 0x7c, 0x75,
	0xac, 0x6e, 0x8d, 0xa8, 0x66, 0xc6, 0x0c, 0x57, 0xde, 0x64, 0x74, 0x70, 0x0f, 0x71, 0x2e, 0xcc,
	0x09, 0x42, 0x1c, 0x30, 0x5d, 0x67, 0x99, 0xe4, 0xe1, 0xcf, 0xa8, 0xc4, 0xb5, 0x9e, 0x83, 0xcf,
	0xf3, 0x69, 0x65, 0xce, 0x6c, 0xe6, 0xbd, 0x44, 0xfb, 0x1b, 0x58, 0xfa, 0x5b, 0x81, 0x93, 0xbb,
	0x22, 0xd9, 0x73, 0x70, 0x2b, 0x97, 0xff, 0x2f, 0xe7, 0xc4, 0x0d, 0xe0, 0x36, 0xda, 0x13, 0xa1,
	0xf4, 0xbf, 0x7f, 0x9c, 0xab, 0x0a, 0x5c, 0xcf, 0xc1, 0x47, 0xc2, 0xaa, 0x8b, 0x1c, 0x59, 0x29,
	0xdd, 0x1a, 0xc2, 0xeb, 0x80, 0xe0, 0xc7, 0xee, 0xb3, 0x0b, 0xa1, 0x32, 0x40, 0x58, 0xdc, 0xc5,
	0x6f, 0x97, 0xdb, 0xfd, 0x90, 0xd0, 0xa1, 0x4d, 0xbd, 0xed, 0x78, 0xb7, 0xc2, 0xf9, 0x61, 0x7a,
	0x57, 0x43, 0xe9, 0xe9, 0x76, 0xea, 0xc6, 0xb3, 0xc4, 0x52, 0x6d, 0xea, 0x69, 0x06, 0x73, 0xf4,
	0xd3, 0x4b, 0x64, 0x67, 0x17, 0x42, 0x40, 0x3b, 0xdc, 0xdb, 0x99, 0x52, 0x6d, 0xeb, 0xa5, 0xbe,
	0xcb, 0x05, 0xa3, 0x6f, 0x7c, 0xca, 0xf5, 0xb5, 0x3b, 0x9b, 0x49, 0x1d, 0xeb, 0x5f, 0xa2, 0x3e,
	0xe1, 0xfa, 0x64, 0xac, 0x5b, 0x45, 0xd6, 0xe1, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x22, 0x96,
	0x01, 0x80, 0x3f, 0x03, 0x00, 0x00,
}
